### ISSUE TITLE
(VSfM) .NET4.x project gets red-line errors when linking to .NET Standard project, but build works (1)

### ISSUE THREAD

**Issue by knocte** [mono/monodevelop#3686]
Steps to reproduce:
1. Create new solution.
2. First project of the solution: a .NET Standard 2.0 F# project library, FooLib.
Note: code created by default is:
```
namespace FooLib

module Say =
    let hello name =
        printfn "Hello %s" name

```
3. Add new project to the solution: template "Other" -> .NET -> Library (C#), name it CsharpUnitTests.
4. Reference library FooLib from CsharpUnitTests. Call it this way:
```
using System;
namespace CsharpUnitTests
{
    public class MyClass
    {
        public MyClass()
        {
            FooLib.Say.hello("world");
        }
    }
}
```
5. Compile solution: it builds successfully, however...

Expected results:
The C# file should be "clean" of underlined-errors.

Current results:
The word "hello" is underlined in red, when hovering it with the mouse, the tooltip says: `use expression body for constructors`

Version: Visual Studio for Mac 7.3.3 (build 5)

> VS bug #571169

**Comment by nosami** [comment]
![image](https://user-images.githubusercontent.com/667194/37210474-b38e421e-23a0-11e8-9eef-4659cca33e6f.png)

Did you add a reference to NetStandard.Library from the C# project?

**Comment by knocte** [comment]
Why would I need that if building the project succeeds?

**Comment by nosami** [comment]
I just took another look at this and it seems to be fixed now. @mrward Any idea when this might have been fixed?

![image](https://user-images.githubusercontent.com/667194/37358197-5a0c5b6e-26e2-11e8-9cd7-89be6d88a063.png)

**Comment by nosami** [comment]
Scratch the last comment, it fails again after cleaning the solution. Looking at the msbuild log, I see that there is an implicit reference to the facade netstandard.dll

```
/reference:/Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/4.7.1-api/Facades/netstandard.dll
```

I suspect that this reference isn't being passed to Roslyn for some reason.

**Comment by nosami** [comment]
I just tested this with the upcoming 7.6 release and this issue has been fixed. I started from a clean solution and didn't add netstandard.dll.

After building the F# project, the red squiggles disappeared from the C# project, so closing.

**Comment by knocte** [comment]
@nosami great! now there's another very related bug which is still not fixed (just tested it with the stable channel, still there): https://github.com/mono/monodevelop/issues/3688
