### ISSUE TITLE
Opening solution closes existing solution

### ISSUE THREAD

**Issue by mhutch** [mono/monodevelop#3791]
Opening a solution on Mac closes the existing solution.

There used to be an option in the "Open" dialog to keep the existing solution, but it's gone. The *Ctrl* keyboard modifier can be used in the "Recent Solutions" menu, but it's completely undiscoverable, and doesn't work when opening solutions via the Open dialog or when by double clicking them in Finder. 

I suggest we add a new dialog:

    The solution 'Foo' is already open. Would you like to close it before opening
    the solution 'Bar', or keep it open?

    [x] Don't ask me again

    [Close existing solution] [Keep existing solution open]

**Comment by jstedfast** [comment]
I think it's under an "Advanced" section (you need to click an expander in the Open dialog).

**Comment by nosami** [comment]
It disappeared on High Sierra

**Comment by mhutch** [comment]
Also the tooltip in the "Recent solutions" menu (that indicated *ctrl* could be used to open the sln without closing the existing one) disappeared in 7.3.

**Comment by mhutch** [comment]
+ @maryanne-exe

**Comment by maryanne-exe** [comment]
With “Don’t ask again” checkbox, I imagine a common user’s behavior is to leave a checkbox unselected and click Ok until they are annoyed by the dialog; It’s one more action to perform and the decision is not urgent.

However, it’s important to inform the user about closing the solution. As Mikayla pointed out, the user will lose undos in a code editor if closes the solution which is valuable data.

An alternative solution for the dialog: ask the user about the preferred setting. Something like:
“Do you want to keep opened solutions in Solution Pad? You can change the behavior later in [Preferences]” Options: “Always close”/“Always keep opened.”

In this case, the user decides once and always has an option to change the behavior if bothered.

**Comment by mhutch** [comment]
Oh, I like that idea, though I think the wording will take some work to get right.

**Comment by mhutch** [comment]
When you open or create a new solution, and you already have a solution open,
    would you like to close the existing solution automatically?

    You can change this preference later in *Preferences -> Project*.

    [Close existing solution] [Keep existing solution open]

**Comment by slluis** [comment]
I don't quite understand what this dialog is asking for. It is too confusing. If I click "Keep existing solution open", does it mean that from now on VS will never close solutions until I change the preference? That's not what we want.

I think the original proposal makes more sense. We can somehow clarify that if "Don't ask me again" is chosen, the dialog can be re-enabled in preferences (that is, the preference is about showing or not the dialog, not about closing or keeping open). We can also show the hint that the same can be done by holding control key when opening a solution.

**Comment by mhutch** [comment]
Isn't it what we want? :)

I can't think of a single other app which, when you open something, automatically closes the thing you had open. They all open a new instance or window, and you can manually close the thing you had open if you want.

**Comment by slluis** [comment]
> I can't think of a single other app which, when you open something, automatically closes the thing you had open

Visual Studio?

> They all open a new instance or window, and you can manually close the thing you had open if you want.

But we don't support that. If we add support for loading the new solution in its own window, then it might make sense to have such preference (enabling it would make VSMac behave like Xcode).

**Comment by mhutch** [comment]
It's not equivalent though, as VS offers several paths to get a new instance. If I double click a solution in explorer, it opens a new VS instance. If I use the start menu to open VS, it opens a new VS instance...

I would be in favor of doing what Xcode does, TBH. I only suggested this as a placeholder until we get multi-window support.

**Comment by slluis** [comment]
I also want to fix it, but I don't think this is a good fix.

**Comment by mhutch** [comment]
I think a not-so-great stopgap fix is better than no fix :)

**Comment by sevoku** [comment]
Just for info: we have fixed the High Sierra issue with the broken open dialog with #3646 and we made the hotkey in the welcome screen more discoverible (incl. the CMD key alternative to CTRL in #3725) with #2836. But supporting multiple windows/instances would be awesome.

**Comment by slluis** [comment]
> I think a not-so-great stopgap fix is better than no fix :)

That's why I proposed to implement what you originally proposed.

**Comment by sevoku** [comment]
@mhutch @slluis since the "Open" dialog issue is fixed and we show the shortcut in the welcome screen on Mac (on Windows the tooltip in the menu should still be there), do we still want the dialog until we support multiple windows? TBH I agree that it's a little bit confusing. And on Mac many apps allow to close a project without asking, if no changes need to be saved (however Maryanne is right about the history, we don't save that).

**Comment by mhutch** [comment]
@sevoku well... it's still not possible to keep the existing solution open when creating a new project or opening a solution by clicking on it in directly in Finder, and on a Mac it's very unexpected for opening a solution to close the existing one, so I think there's still a pretty strong case to be made for it

@maryanne-exe I like the idea of combining this with the "Save unchanged changes" dialog 👍

**Comment by migueldeicaza** [comment]
My take is that MonoDevelop on Mac is not following the platform guidelines to open a new window when a new document is created, and this is the source of various of the usability wrinkles that we are discussing here.

In my opinion, we need to fully embrace the Apple idioms.  If we do not do this, we will continue to fight the platform, which is exactly what is going on here.

Concretely, what we need to do:

- [ ] MonoDevelop's behavior when opening a new solution is to open a new toplevel window for the solution.   Currently we close the current solution - this is the bug.
- [ ] We should support the application launch protocol so that when we get a request to open a new solution, the behavior is to open the new window, without closing any existing open documents.

This means that we should not need a dialog box that says "Hey, do you want to close what you currently have open", which is both unnatural on OSX and is poor UI as pointed out before.

I do not have a strong opinion about keeping the obscure/non-obvious "Close current solution" in the File dialog/options section.

**Comment by sevoku** [comment]
Yeah, I strongly agree with that. We need support for multiple IDE windows, which would solve all the mentioned and related issues. See also the discussion in #3800. Anything else is just workarounding initially wrong design/behaviour (well maybe it's better to call it "historical" design).

However it's not a simple task and we even don't officially support multiple MD instances on Mac. First of all we need a native shell and and support for multiple workbenches. The main problem I see besides the native shell (which is already long planned) is that really many things depend on the static workbench and main IDE window. It goes really deep into the whole project infrastructure and many other core things.

**Comment by mhutch** [comment]
@sevoku why is this dependent on the native shell?

**Comment by mhutch** [comment]
Hypothetically, couldn't we just have multiple workbench instances (`IdeApp.Workbenches`) and make the `IdeApp.Workbench` property use the focused one? The project infrastructure already works with multiple open solutions.

( i know it's not quite that simple, but i don't think it's super complex either)

**Comment by sevoku** [comment]
Well, its not directly dependent, maybe "connected" is better. We have many things which rely on the main IDE window, and also the shell directly depends on it (one main IDE window and workbench). Of course we could do first the one than the other, but it would mean a higher time investment cause both features involve changes in same infrastructure parts.

So IMO we should do it once for both at the same time in the "right" well designed way, since my concern is that if we do one of them first, well keep iterating it forever unti the other one is finished.

Whatever way we choose, the multiple IDE window part is not super complex, of course not, but it's not something that can be fixed within a couple of days. The base change is not complex at all, but I've got the feeling that it won't be as simple as making the static `IdeApp.Workbench` use the focused one. And that'll be the biggest part: we have many very different things which rely on it, which includes many workaround for different stuff (can't tell right now what and where exactly, but I saw it many times). It'll be a long rat tail.

**Comment by mhutch** [comment]
I feel like this is one of these things where we won't know the full scope of work until we get into the implementation.

I get your point regarding doing both at the same time, but I don't think the coupling is that great, and doing things separately means we can release them more quickly.

**Comment by slluis** [comment]
> I feel like this is one of these things where we won't know the full scope of work until we get into the implementation.

Completely agree.

It is true that all the code assumes that there is only one top level window, but it is also true that there will be only one active top level window at a time.

**Comment by mkrueger** [comment]
IMO  we should remove the multiple solution open at once thing completely. Opening multiple solutions can open a new instance.

That would make interop with VS.NET ideoms, code and addins a lot easier…

**Comment by mhutch** [comment]
One process per solution window brings its own complications though. There's state that would need to be shared, such as preferences, search history, and identity; singleton dialogs like Find in Files and Preferences; commands that apply to the whole app like Hide all Windows and Quit; and there would need to be a single dock icon.
