### ISSUE TITLE
Red squiggles have a tendency to stick around

### ISSUE THREAD

**Issue by garuma** [mono/monodevelop#3858]
On master, it may happen that the error provider that powers the editor squiggles get out of date with the current state of the document. Usually the patterns goes like:

 1. The document is in an invalid state. Highlighting is messed up and squiggles are displayed
 2. Issues is fixed, classification kicks in again and highlighting it now correct
 3. Red squiggle stick around and display the same error than before

All in one it seems like the error list is kept from one document state to the other.

This may likely be fixed by https://github.com/mono/monodevelop/pull/3636

> VS bug #569966

**Comment by Therzok** [comment]
https://github.com/dotnet/roslyn/issues/24714

Related

**Comment by mrward** [comment]
This is something I have seen with recent master builds of VS Mac. Sometimes closing and re-opening the file gets rid of the warnings/errors.

**Comment by Therzok** [comment]
@garuma probably fixed via https://github.com/mono/monodevelop/issues/4149

**Comment by garuma** [comment]
Seems to now be working in recent versions

**Comment by mrward** [comment]
Still seeing this, but less often in d15-7 builds Re-opening.

**Comment by mkrueger** [comment]
@Marius: can be related to the recent work you did there - if you think it's closed just close that one.

**Comment by Therzok** [comment]
I think https://github.com/mono/monodevelop/pull/4839 fixed it.
