### ISSUE TITLE
Double click text selection is often blocked by new tooltip

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4818]
Double clicking to select some text often seems to result in the tooltip being clicked and not the text itself.

![doubleclickpreventedbytooltip](https://user-images.githubusercontent.com/372361/40120137-6d6c9672-5916-11e8-8db5-86dd4eb34226.gif)

I think the tooltip appears too close to the caret. The original tooltip was below the line. You cannot click the original tooltip window since it disappears when you try to move the caret over it.

> VS bug [#617309](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/617309)

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.6.0.831 (master)

Pull Request #4826 merged by: Kirill Osenkov
Author: mono/dev/kirillo
Commit: a8e3893b363adc3020909191951d5b2e90a36459 (mono/monodevelop)

**Comment by mrward** [comment]
Doesn't this problem still happen for those files that use this new tooltip, such as with web files such as .css? The fix applied just hides the tooltip for C# files.

For example, if you create a new ASP.NET Core MVC project, then open the site.css and mis-type a css property:

```
/* Wrapping element */
/* Set some basic padding to keep content from hitting the edges */
.body-content {
	padding-left: 15px;
	paddinng-right: 15px;
}
```

Then if you hover over the mis-typed paddinng-right the new tooltip blocks the click

**Comment by KirillOsenkov** [comment]
Yes, we do need to fix the actual problem, my PR was just to stop the bleeding in the common case.

**Comment by mkrueger** [comment]
https://github.com/mono/monodevelop/pull/4977 could maybe fix the problem it removes the old style tooltips completely.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.8.0.951 (master)

Pull Request #6075 merged by: Lluis Sanchez
Author: mono
Commit: cff04dc9f05da5e8246d88ed275416c8e8ec7e42 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.0.0.471 (release-8.0)

Pull Request #6075 merged by: Lluis Sanchez
Author: mono
Commit: cff04dc9f05da5e8246d88ed275416c8e8ec7e42 (mono/monodevelop)

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #6075 merged by: Lluis Sanchez
Author: mono
Commit: cff04dc9f05da5e8246d88ed275416c8e8ec7e42 (xamarin/monodevelop)
