### ISSUE TITLE
Error when cloning new Git repository locks IDE main menu

### ISSUE THREAD

**Issue by mrward** [mono/monodevelop#4862]
VS Mac 7.5.1 and 7.6.0.852 (master)

1. Tried to checkout/clone a new GitHub repository using Version Control - Git Checkout...
2. There was an error message dialog that briefly pops up but goes away.
3. Then the status bar shows an error: `Version control operation failed: Failed to start SSH session: Unable to exchange encryption key`.
4. All main menu items are disabled.
5. The status bar stop button does not seem to stop the version control action.
6. Have to force quit VS Mac.

IDE log:
https://gist.github.com/mrward/9c9cbe78df44efbe52885074e40628e2

My ssh local key needs a username/password to be used which might be the cause of the error - however the error should be handled and you should not have to use force quit to close VS Mac even if you cannot checkout the git repository.

> VS bug [#619788](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/619788)

**Comment by Therzok** [comment]
I can repro the exception, but cannot repro the UI lockup. Is this still happening?

**Comment by mrward** [comment]
Yes with VS Mac 7.6.0.1866 (release-7.6) the UI problem still occurs for me. All main menus are disabled. I have to force quit.

**Comment by xamarin-release-manager** [comment]
Fixed in version 7.7.0.680 (master)

Pull Request #5439 merged by: Lluis Sanchez
Author: mono
Commit: 0a990b3ab32c1597da7ba353d447eb79568789fe (mono/monodevelop)

**Comment by mrward** [comment]
Tried the VisualStudioForMac-Preview-7.7.0.671.dmg with the fix and still seeing the same behaviour.

```
Build Information
Release ID: 707000671
Git revision: 39bf9da4cfe765101313b7850803222cb19d4b1f
Build date: 2018-07-18 13:24:11+00
Build branch: vcs-freeze
Xamarin extensions: f1c83ea53788b37d3392c6509c96e2a9d8be0f04
```

**Comment by Therzok** [comment]
Devdiv bug was closed.

Fixed via https://github.com/mono/monodevelop/pull/5450
https://github.com/mono/monodevelop/pull/5447

**Comment by xamarin-release-manager** [comment]
Fixed in version 8.6.0.802 (master)

Pull Request #5439 merged by: Lluis Sanchez
Author: mono
Commit: 0a990b3ab32c1597da7ba353d447eb79568789fe (xamarin/monodevelop)

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-35] Comment by **xamarinc**



Fixed in version 8.6.0.802 (master)



Author: therzok  
 Commit: 9769120bce1ec6374e8d5ddbe274a655683e16d7 (xamarin/monodevelop)
