### ISSUE TITLE
New Editor crash after writing commas - {}

### ISSUE THREAD

**Issue by madrvojt** [mono/monodevelop#8165]
New editor crash after creating commas "{}" in latest 8.2 preview version.
```
**Visual Studio Error Report:**

{
	"payload" : 
{
  "protocol_version" : "0.0.4",
  "configuration" : {
    "version" : "(6.0.0.296) (2019-02/1e9f3bfbc5a)",
    "tlc" : "normal",
    "sigsgev" : "altstack",
    "notifications" : "kqueue",
    "architecture" : "amd64",
    "disabled_features" : "none",
    "smallconfig" : "disabled",
    "bigarrays" : "disabled",
    "softdebug" : "enabled",
    "interpreter" : "enabled",
    "llvm_support" : "0",
    "suspend" : "hybrid"
  },
  "memory" : {
    "Resident Size" : "1129586688",
    "Virtual Size" : "7764025344",
    "minor_gc_time" : "35049374",
    "major_gc_time" : "8053453",
    "minor_gc_count" : "462",
    "major_gc_count" : "14",
    "major_gc_time_concurrent" : "51342459"
 },
  "threads" : [
 {
    "is_managed" : false,
    "offset_free_hash" : "0x60ffba83e",
    "offset_rich_hash" : "0x60ffba897",
    "crashed" : true,
    "native_thread_id" : "0x0",
    "thread_info_addr" : "0x0",
    "exceptions" : [
  {
      "type" : "System.NullReferenceException",
      "managed_frames" : [
   {
        "is_managed" : "true",
        "guid" : "6518D0E6-0CA8-4F6B-915C-07341A031A32",
        "token" : "0x600015f",
        "native_offset" : "0x13",
        "filename" : "System.Collections.Immutable.dll",
        "sizeofimage" : "0x4a000",
        "timestamp" : "0x5afb3def",
        "il_offset" : "0xffffffff"
    }
,
   {
        "is_managed" : "true",
        "guid" : "6518D0E6-0CA8-4F6B-915C-07341A031A32",
        "token" : "0x600001c",
        "native_offset" : "0xaa",
        "filename" : "System.Collections.Immutable.dll",
        "sizeofimage" : "0x4a000",
        "timestamp" : "0x5afb3def",
        "il_offset" : "0xffffffff"
    }
,
   {
        "is_managed" : "true",
        "guid" : "67775775-5820-451C-B538-6A30B38B9F0E",
        "token" : "0x60000a4",
        "native_offset" : "0x162",
        "filename" : "Microsoft.VisualStudio.Language.Implementation.dll",
        "sizeofimage" : "0x32000",
        "timestamp" : "0xc5fb1def",
        "il_offset" : "0x0000d"
    }
,
   {
        "is_managed" : "true",
        "guid" : "67775775-5820-451C-B538-6A30B38B9F0E",
        "token" : "0x60000ef",
        "native_offset" : "0x184",
        "filename" : "Microsoft.VisualStudio.Language.Implementation.dll",
        "sizeofimage" : "0x32000",
        "timestamp" : "0xc5fb1def",
        "il_offset" : "0x00019"
    }
,
   {
        "is_managed" : "true",
        "guid" : "B0C858D4-96CA-4FF1-9381-13CE8B7AA1EC",
        "token" : "0x6000031",
        "native_offset" : "0xf1",
        "filename" : "Microsoft.VisualStudio.Text.UI.dll",
        "sizeofimage" : "0x26000",
        "timestamp" : "0xc12c8222",
        "il_offset" : "0xffffffff"
    }
,
   {
        "is_managed" : "true",
        "guid" : "69300B48-01C2-46B3-AC70-275BE363265F",
        "token" : "0x6000045",
        "native_offset" : "0x9a",
        "filename" : "Microsoft.VisualStudio.UI.Text.Commanding.Implementation.dll",
        "sizeofimage" : "0xe000",
        "timestamp" : "0x80698464",
        "il_offset" : "0xffffffff"
    }
,
   {
        "is_managed" : "true",
        "guid" : "63A185BC-CD64-4D7E-A719-9CA475C500F2",
        "token" : "0x00000",
        "native_offset" : "0xa2",
        "filename" : "mscorlib.dll",
        "sizeofimage" : "0x464000",
        "timestamp" : "0xfdc9bce0",
        "il_offset" : "0xffffffff"
    }
,
   {
        "is_managed" : "true",
        "guid" : "69300B48-01C2-46B3-AC70-275BE363265F",
        "token" : "0x6000010",
        "native_offset" : "0x662",
        "filename" : "Microsoft.VisualStudio.UI.Text.Commanding.Implementation.dll",
        "sizeofimage" : "0xe000",
        "timestamp" : "0x80698464",
        "il_offset" : "0xffffffff"
    }
,
   {
        "is_managed" : "true",
        "guid" : "7DB67B1F-A259-4CA1-99A8-4BF142077214",
        "token" : "0x6000762",
        "native_offset" : "0xb0",
        "filename" : "Microsoft.VisualStudio.UI.Text.Cocoa.View.Implementation.dll",
        "sizeofimage" : "0xcc000",
        "timestamp" : "0xc2b3bc70",
        "il_offset" : "0xffffffff"
    }
,
   {
        "is_managed" : "true",
        "guid" : "7DB67B1F-A259-4CA1-99A8-4BF142077214",
        "token" : "0x600077c",
        "native_offset" : "0x142",
        "filename" : "Microsoft.VisualStudio.UI.Text.Cocoa.View.Implementation.dll",
        "sizeofimage" : "0xcc000",
        "timestamp" : "0xc2b3bc70",
        "il_offset" : "0x0000d"
    }
,
   {
        "is_managed" : "true",
        "guid" : "7DB67B1F-A259-4CA1-99A8-4BF142077214",
        "token" : "0x600097e",
        "native_offset" : "0x122",
        "filename" : "Microsoft.VisualStudio.UI.Text.Cocoa.View.Implementation.dll",
        "sizeofimage" : "0xcc000",
        "timestamp" : "0xc2b3bc70",
        "il_offset" : "0x00018"
    }
,
   {
        "is_managed" : "true",
        "guid" : "182E7179-F569-44BE-B10C-588DE940CE22",
        "token" : "0x6004d98",
        "native_offset" : "0x43",
        "filename" : "MonoDevelop.Ide.dll",
        "sizeofimage" : "0x6da000",
        "timestamp" : "0xca55f0e6",
        "il_offset" : "0x00000"
    }
,
   {
        "is_managed" : "true",
        "guid" : "182E7179-F569-44BE-B10C-588DE940CE22",
        "token" : "0x6000042",
        "native_offset" : "0x9b",
        "filename" : "MonoDevelop.Ide.dll",
        "sizeofimage" : "0x6da000",
        "timestamp" : "0xca55f0e6",
        "il_offset" : "0xffffffff"
    }
,
   {
        "is_managed" : "true",
        "guid" : "182E7179-F569-44BE-B10C-588DE940CE22",
        "token" : "0x6000043",
        "native_offset" : "0x1ca",
        "filename" : "MonoDevelop.Ide.dll",
        "sizeofimage" : "0x6da000",
        "timestamp" : "0xca55f0e6",
        "il_offset" : "0x00000"
    }
,
   {
        "is_managed" : "true",
        "guid" : "40F46E55-EB67-454A-B904-DC9E5644A3A1",
        "token" : "0x6003b45",
        "native_offset" : "0xd6",
        "filename" : "gtk-sharp.dll",
        "sizeofimage" : "0x16a000",
        "timestamp" : "0x0",
        "il_offset" : "0x00016"
    }

   ]  }
 ]
}
]
},
	"parameters" : 
{
		"ApplicationBundleId" : "com.microsoft.visual-studio",
		"ApplicationVersion" : "8.2.0.1064",
		"ApplicationBitness" : "x64",
		"ApplicationName" : "Visual Studio",
		"BlameModuleName" : "Mono Exception",
		"BlameModuleVersion" : "6.0.0.296 (2019-02/1e9f3bfbc5a)",
		"BlameModuleOffset" : "0x0",
		"ExceptionType" : "0x02000000",
		"StackChecksum" : "0x60ffba83e",
		"StackHash" : "0x60ffba897",
		"Extra" : 
		{
			"sessionId" : "074c41b8-a26f-444f-a59c-0dcdab232f3a"
		},
		"OSVersion" : "18.6.0",
		"LanguageID" : "0x7f",
		"SystemManufacturer" : "apple",
		"SystemModel" : "MacBookPro11,1",
		"EventType" : "AppleAppCrash"
	}
}

**Info About VS:**


=== Visual Studio Enterprise 2019 for Mac (Preview) ===

Version 8.2 Preview (8.2 build 1064)
Installation UUID: e725d82d-70bc-49af-b281-bc524c611deb
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.83 (d16-2 / f08d4e3e)

	Package version: 600000296

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.296 (2019-02/1e9f3bfbc5a) (64-bit)
	Package version: 600000296

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.1.11
SDK: /usr/local/share/dotnet/sdk/2.2.300/Sdks
SDK Versions:
	2.2.300
	2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Android ===

Version: 9.4.0.34 (Visual Studio Enterprise)
Commit: xamarin-android/d16-2/7cce305
Android SDK: /Users/madrvojt/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@c6edaa62f94
Java.Interop: xamarin/java.interop/d16-2@b2b2610
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@4f717b6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/madrvojt/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-05 16:31:08 UTC

=== Xamarin Designer ===

Version: 16.2.0.347
Hash: 9e8bf8f7c
Branch: remotes/origin/d16-2
Build date: 2019-07-03 00:59:58 UTC

=== Xamarin.Mac ===

Version: 5.14.0.91 (Visual Studio Enterprise)
Hash: 2f1cc7bb
Branch: d16-2
Build date: 2019-06-07 02:49:23-0400

=== Xamarin.iOS ===

Version: 12.14.0.91 (Visual Studio Enterprise)
Hash: 2f1cc7bb
Branch: d16-2
Build date: 2019-06-07 02:49:22-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802001064
Git revision: 0448409d5cea4c424f1d1c3184eedb600f35a325
Build date: 2019-07-05 18:39:33+00
Build branch: release-8.2
Xamarin extensions: b61aae02a21cf72143ea6737d9ddad3bed69a336

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

XAML Styler 1.1.2
Xamarin.HotReload 1.0.0.2831126
MFractor 3.8.9
NuGet Package Management Extensions 0.18

```

> VS bug [#950519](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/950519)

**Comment by Therzok** [comment]
Hey @madrvojt , could you please also attach the IDE log file for the crashing session? They can be found via Help -> Open Log Directory or at `~/Library/Logs/VisualStudio/8.0`

**Comment by madrvojt** [comment]
Hello @Therzok,

there is log - [VS8.2CrashLog.zip](https://github.com/mono/monodevelop/files/3414839/VS8.2CrashLog.zip)

If you need more info, please let me know!

Updated info about IDE:

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.2 (build 1090)
Installation UUID: 41a324bb-8920-4f96-8316-c501664d8353
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.83 (d16-2 / f08d4e3e)

	Package version: 600000311

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.1.11
SDK: /usr/local/share/dotnet/sdk/2.2.300/Sdks
SDK Versions:
	2.2.300
	2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Android ===

Version: 9.4.0.51 (Visual Studio Enterprise)
Commit: xamarin-android/d16-2/9fa7775
Android SDK: /Users/madrvojt/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/madrvojt/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-10 20:46:18 UTC

=== Xamarin Designer ===

Version: 16.2.0.347
Hash: 9e8bf8f7c
Branch: remotes/origin/d16-2
Build date: 2019-07-03 00:59:58 UTC

=== Xamarin.Mac ===

Version: 5.14.0.110 (Visual Studio Enterprise)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:43-0400

=== Xamarin.iOS ===

Version: 12.14.0.110 (Visual Studio Enterprise)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802001090
Git revision: e7cb5ab98845ed937de94df83e2818cb4671aa13
Build date: 2019-07-12 16:16:40+00
Build branch: release-8.2
Xamarin extensions: 5a41faecc2127f5054df93eea5acfcc0884579b2

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

XAML Styler 1.1.2
Xamarin.HotReload 1.0.0.2831126
NuGet Package Management Extensions 0.19
MFractor 3.8.9

**Comment by sandyarmstrong** [comment]
This was fixed in 8.2.0.1101.

**Comment by madrvojt** [comment]
@sandyarmstrong error is still there! There is new log 👍 
[Crash_latest_stavble.zip](https://github.com/mono/monodevelop/files/3429907/Crash_latest_stavble.zip)

Updated info about IDE:

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.2 (build 1105)
Installation UUID: 31865e51-ddc7-4416-a265-cdb092db73b2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000311

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.1.11
SDK: /usr/local/share/dotnet/sdk/2.2.300/Sdks
SDK Versions:
	2.2.300
	2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.110 (Visual Studio Enterprise)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:43-0400

=== Xamarin.iOS ===

Version: 12.14.0.110 (Visual Studio Enterprise)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

=== Xamarin Designer ===

Version: 16.2.0.354
Hash: 5f80a14f8
Branch: remotes/origin/d16-2
Build date: 2019-07-11 17:28:26 UTC

=== Xamarin.Android ===

Version: 9.4.0.51 (Visual Studio Enterprise)
Commit: xamarin-android/d16-2/9fa7775
Android SDK: /Users/madrvojt/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/madrvojt/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802001105
Git revision: a187f6852ae62ba52b944b47e53702957edfcf7b
Build date: 2019-07-22 18:20:10+00
Build branch: release-8.2
Xamarin extensions: 34bd2378d8d707df25989727c23ce68d9a232a67

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.HotReload 1.0.0.2831126
XAML Styler 1.1.4
NuGet Package Management Extensions 0.19
MFractor 3.8.9

**Comment by sandyarmstrong** [comment]
@madrvojt thanks for retesting so quickly! This fix ended up not making it for 8.2.0 or 8.3 P1, apparently, but this has now been corrected in all branches and should be fixed with the next releases.
